#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use BladeUI\Icons\Console\GenerateCommandBuilder;

GenerateCommandBuilder::create('blade-fontawesome')
    ->fromNpmPackage('@fortawesome/fontawesome-free') // Optionally specify an `npm` package to load from
    ->fromSourceSvgDirectory('/svgs') // Specify a directory, if an npm package isn't set, this can be anywhere
    ->withIconSets([
        'regular'   => 'far-',
        'brands'    => 'fab-',
        'solid'     => 'fas-',
    ])
    ->withSvgNormalisation(function (string $tempFilepath, string $iconSet) {
        $doc = new DOMDocument();
        $doc->load($tempFilepath);
        /**
         * @var DOMElement $svgElement
         */
        $svgElement = $doc->getElementsByTagName('svg')[0];
        $svgElement->setAttribute('fill', 'currentColor');
        $doc->save($tempFilepath);

        $svgLine = trim(file($tempFilepath)[1]);
        file_put_contents($tempFilepath, $svgLine);
    })
    ->run();
