#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use BladeUI\Icons\Console\IconSetConfig;
use BladeUI\Icons\Console\GenerateCommandBuilder;

GenerateCommandBuilder::create('blade-fontawesome')
    ->fromNpmPackage('@fortawesome/fontawesome-free') // Optionally specify an `npm` package to load from
    ->fromSourceSvgDirectory('/svgs') // Specify a directory, if an npm package isn't set, this can be anywhere
    ->withIconSets([
        IconSetConfig::create('regular'),
        IconSetConfig::create('brands'),
        IconSetConfig::create('solid'),
    ])
    ->withSvgNormalisation(function (string $tempFilepath, IconSetConfig $iconSet) {
        /** @var string $svgContent */
        $svgContent = file_get_contents($tempFilepath);
        $svgContent = str_replace('<svg ', '<svg fill="currentColor" ', $svgContent);
        file_put_contents($tempFilepath, $svgContent);
    })
    ->clearDestinationDirectory()
    ->run();
