name: Auto Update

on:
  workflow_dispatch:
  schedule:
  - cron: '0 */6 * * *'

jobs:
  versions:
    runs-on: ubuntu-latest

    name: Get Versions

    outputs:
      current: ${{ steps.current-version.outputs.version }}
      latest: ${{ steps.latest-version.outputs.version }}

    steps:

    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - id: current-version
      name: Get current Font Awesome version
      run: echo "version=$(tr -d '[:space:]' < .version)" >> "$GITHUB_OUTPUT"

    - id: latest-version
      name: Get latest Font Awesome version
      run: echo "version=$(npm view @fortawesome/fontawesome-free version)" >> "$GITHUB_OUTPUT"

    - name: Output versions
      run: |
        echo "Current release: ${{ steps.current-version.outputs.version }}"
        echo "Latest release: ${{ steps.latest-version.outputs.version }}"

  update:
    runs-on: ubuntu-latest

    name: Update Font Awesome

    needs: [versions]

    if: needs.versions.outputs.current != needs.versions.outputs.latest

    env:
      CURRENT_VERSION: ${{ needs.versions.outputs.current }}
      LATEST_VERSION: ${{ needs.versions.outputs.latest }}
      BRANCH: feature/update-${{ needs.versions.outputs.latest }}

    steps:

    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup PHP
      uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
      with:
        php-version: 8.4
        coverage: none

    - name: Install Dependencies
      run: composer update --prefer-stable --no-interaction --prefer-dist --no-progress --ansi

    - name: Update to latest version
      run: npm install "@fortawesome/fontawesome-free@${{ env.LATEST_VERSION }}" --save-dev

    - name: Compile icons to resources directory
      run: vendor/bin/blade-icons-generate

    - name: Update version in ".version"
      run: echo ${{ env.LATEST_VERSION }}>./.version

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Commit changes
      run: |
        git add -A
        git commit -m "chore: update to Font Awesome v${{ env.LATEST_VERSION }}"

    - name: Update test snapshots
      run: vendor/bin/pest --update-snapshots

    - name: Commit changes
      id: commit_snapshots
      run: |
        git add tests/.pest/snapshots
        git commit -m "tests: update snapshots for v${{ env.LATEST_VERSION }}"
        echo "commit_long_sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

    - name: Create PR for latest version
      uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
      with:
        title: "chore: update to Font Awesome v${{ env.LATEST_VERSION }}"
        branch: "feature/auto-update-${{ env.LATEST_VERSION }}"
        body: |
          This updates from [${{ env.CURRENT_VERSION }}](https://github.com/FortAwesome/Font-Awesome/releases/tag/${{ env.CURRENT_VERSION }}) to [${{ env.LATEST_VERSION }}](https://github.com/FortAwesome/Font-Awesome/releases/tag/${{ env.LATEST_VERSION }}).

          Check out the differences: [`${{ env.CURRENT_VERSION }}` ... `${{ env.LATEST_VERSION }}`](https://github.com/FortAwesome/Font-Awesome/compare/${{ env.CURRENT_VERSION }}...${{ env.LATEST_VERSION }})

          Please check for any breaking or notable changes before merging.
          - [Changelog](https://fontawesome.com/docs/changelog)
          - [Upgrade Guide](https://github.com/FortAwesome/Font-Awesome/blob/${{ env.LATEST_VERSION }}/UPGRADING.md#upgrading-guide)

          Please also check that the snapshots were updated successfully in commit: [${{ steps.commit_snapshots.outputs.commit_long_sha }}](https://github.com/owenvoke/blade-fontawesome/commit/${{ steps.commit_snapshots.outputs.commit_long_sha }}).
